name: icons

on:
  schedule:
    - cron: '0 1 * * 1'

  workflow_dispatch:

env:
  OUTPUT_ROOT_DIR: packages/icon-files/

jobs:
  icons:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: pnpm

      - name: Prepare deps
        run: |
          pnpm install --frozen-lockfile
          pnpm run build --recursive --resume-from @charcoal-ui/icons-cli

      - name: Export
        env:
          FIGMA_FILE_URL: ${{ secrets.FIGMA_FILE_URL }}
          FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
        run: pnpm icons-cli figma:export

      - name: Optimize
        run: pnpm icons-cli svg:optimize --ignoreFile ./misc/icons-cli-denylist

      - name: Generate source
        run: pnpm icons-cli files:generate

      - name: Generate github token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.CHARCOAL_BOT_APP_ID }}
          private_key: ${{ secrets.CHARCOAL_BOT_PRIVATE_KEY }}

      - name: Create a Pull Request
        env:
          GITHUB_ACCESS_TOKEN: ${{ steps.generate_token.outputs.token }}
          GITHUB_REPO_OWNER: pixiv
          GITHUB_REPO_NAME: charcoal
          GITHUB_DEFAULT_BRANCH: main
        run: pnpm icons-cli github:pr
